[features]
resolution = true
skip-lint = false

[programs.localnet]
soondex = "8BPmoTqwHpFGECrtmWbDSz8wDXj5X7e32qdkLrNhQVqy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.soo.network/rpc" 
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
